#ifndef COMMAND_H
#define COMMAND_H

#include <string>

// type of game move
enum class CommandType
{
	// gameplay commands
	LEFT = 0,
	RIGHT,
	DOWN,
	CLOCKWISE,
	COUNTERCLOCKWISE,
	DROP,
	LEVELUP,
	LEVELDOWN,
	NORANDOM_FILE,
	RANDOM,
	SEQUENCE_FILE,
	RESTART,
	HINT,
	NOT_A_GAME_MOVE,

	// test commands
	I,
	J,
	L,
	S,
	Z,
	O,
	T,

	// program control commands
	QUIT,

	UNDEFINED_COMMAND
};

// commands are generated by views and interpreted
// by a CommandInterpreter instance
struct Command
{
	Command();
	Command(CommandType);
	CommandType type;
	// for some commands, a message string may be desired
	std::string message;
};

typedef CommandType CMD;

#endif // COMMAND_H
